package mx.com.ado.auditoria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AplicacionEncuestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionEncuestaAllPropertiesEquals(AplicacionEncuesta expected, AplicacionEncuesta actual) {
        assertAplicacionEncuestaAutoGeneratedPropertiesEquals(expected, actual);
        assertAplicacionEncuestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionEncuestaAllUpdatablePropertiesEquals(AplicacionEncuesta expected, AplicacionEncuesta actual) {
        assertAplicacionEncuestaUpdatableFieldsEquals(expected, actual);
        assertAplicacionEncuestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionEncuestaAutoGeneratedPropertiesEquals(AplicacionEncuesta expected, AplicacionEncuesta actual) {
        assertThat(actual)
            .as("Verify AplicacionEncuesta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionEncuestaUpdatableFieldsEquals(AplicacionEncuesta expected, AplicacionEncuesta actual) {
        assertThat(actual)
            .as("Verify AplicacionEncuesta relevant properties")
            .satisfies(a -> assertThat(a.getEnlaceUnico()).as("check enlaceUnico").isEqualTo(expected.getEnlaceUnico()))
            .satisfies(a -> assertThat(a.getFechaAplicacion()).as("check fechaAplicacion").isEqualTo(expected.getFechaAplicacion()))
            .satisfies(a -> assertThat(a.getRespuestaEncuesta()).as("check respuestaEncuesta").isEqualTo(expected.getRespuestaEncuesta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAplicacionEncuestaUpdatableRelationshipsEquals(AplicacionEncuesta expected, AplicacionEncuesta actual) {
        assertThat(actual)
            .as("Verify AplicacionEncuesta relationships")
            .satisfies(a -> assertThat(a.getEncuestado()).as("check encuestado").isEqualTo(expected.getEncuestado()))
            .satisfies(a -> assertThat(a.getEncuesta()).as("check encuesta").isEqualTo(expected.getEncuesta()));
    }
}
