package mx.com.ado.auditoria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EncuestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAllPropertiesEquals(Encuesta expected, Encuesta actual) {
        assertEncuestaAutoGeneratedPropertiesEquals(expected, actual);
        assertEncuestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAllUpdatablePropertiesEquals(Encuesta expected, Encuesta actual) {
        assertEncuestaUpdatableFieldsEquals(expected, actual);
        assertEncuestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaAutoGeneratedPropertiesEquals(Encuesta expected, Encuesta actual) {
        assertThat(actual)
            .as("Verify Encuesta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaUpdatableFieldsEquals(Encuesta expected, Encuesta actual) {
        assertThat(actual)
            .as("Verify Encuesta relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getVigenciaDesde()).as("check vigenciaDesde").isEqualTo(expected.getVigenciaDesde()))
            .satisfies(a -> assertThat(a.getVigenciaHasta()).as("check vigenciaHasta").isEqualTo(expected.getVigenciaHasta()))
            .satisfies(a -> assertThat(a.getStructuraJson()).as("check structuraJson").isEqualTo(expected.getStructuraJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestaUpdatableRelationshipsEquals(Encuesta expected, Encuesta actual) {
        // empty method
    }
}
