package mx.com.ado.auditoria.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EncuestadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestadoAllPropertiesEquals(Encuestado expected, Encuestado actual) {
        assertEncuestadoAutoGeneratedPropertiesEquals(expected, actual);
        assertEncuestadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestadoAllUpdatablePropertiesEquals(Encuestado expected, Encuestado actual) {
        assertEncuestadoUpdatableFieldsEquals(expected, actual);
        assertEncuestadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestadoAutoGeneratedPropertiesEquals(Encuestado expected, Encuestado actual) {
        assertThat(actual)
            .as("Verify Encuestado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestadoUpdatableFieldsEquals(Encuestado expected, Encuestado actual) {
        assertThat(actual)
            .as("Verify Encuestado relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getClaveEmpleado()).as("check claveEmpleado").isEqualTo(expected.getClaveEmpleado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEncuestadoUpdatableRelationshipsEquals(Encuestado expected, Encuestado actual) {
        // empty method
    }
}
